### PR TITLE
[#179606510] Enable paas-admin to use a CF dev environment during development

### PR DESCRIPTION
**Pull request by AP-Hunt**
What
----

Enables paas-admin to use the APIs of a CF dev env. This is a quality of life enhancement.

Run `npm run start:dev:with-cf-dev-env DEPLOY_ENV`. 

It will only work in development environments once [an enabling PR in `paas-cf`](https://github.com/alphagov/paas-cf/pull/2848) has gone out. It's currently only deployed in `dev03`.

How to review
-------------
Code review
Try it out

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

### CODE REVIEW

**Review by kr8n3r — COMMENTED** [review]
~~looks ok and the first bit worked in testing, but to check the whole script, https://github.com/alphagov/paas-cf/pull/2848 needs to be merged first~~

worked on dev03

**Review by cadmiumcat — APPROVED** [review]
This worked for me in `dev03` 🥳

**Review by kr8n3r — APPROVED** [review]

**Comment by kr8n3r** [comment]
what do we need to get metrics page working?

`"req":{"method":"GET","url":"/organisations/a28d782d-77b5-4742-8d39-b62533cdf239/spaces/f4622458-e7f7-4279-8837-8eb15fbff055/services/b5f189cd-8d74-4584-a74e-f7820c575c53/metrics?rangeStart=2022-02-15T09%3A49%3A07Z&rangeStop=2022-02-16T09%3A49%3A07Z"},"errno":-61,"code":"ECONNREFUSED","syscall":"connect","address":"0.0.0.0","port":1341,"$metadata":{"attempts":1,"totalRetryDelay":0},"stack":"Error: connect ECONNREFUSED 0.0.0.0:1341\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)","type":"Error","msg":"connect ECONNREFUSED 0.0.0.0:1341"}`

**Comment by AP-Hunt** [comment]
I'm thinking this needs AWS credentials. I'll make a small tweak to this later today to enable you to run it in a way that gives it AWS creds.

**Comment by AP-Hunt** [comment]
I originally thought running the command in a context with AWS creds (e.g. `gds aws ACCOUNT -- npm run ...`) would work. However, it looks like we get `InvalidClientTokenId: The security token included in the request is invalid` errors from CloudWatch when we do that.

**Comment by cadmiumcat** [comment]
Try it now, running ` gds aws paas-dev-admin -- npm run start:dev:with-cf-dev-env dev03`

**Comment by kr8n3r** [comment]
yeah all good now

**Pull request closed without merging**
