### PR TITLE
Email org owners via PaaSmin

### PR DESCRIPTION
**Pull request by 0atman**
What
----

Sometimes we need to contact the owners of a CF org via email. At the moment we do that by harvesting their email addresses from PaaSmin and sending an email from the support address via Gmail.

It would be nice (and easier) if we could send an email directly from PaaSmin 

How to review
-------------
Tests pass, emails send

Who can review
---------------

Paas devs

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

### CODE REVIEW

**Comment by 0atman** [comment]
First in-page mockup

Screenshot 2021-10-04 at 14-56-23 Platform Administrator

**Comment by 0atman** [comment]
Moved to its own page

Screenshot 2021-10-05 at 11-21-53 Platform Administrator

Screenshot 2021-10-05 at 11-24-36 Create Organisation

**Comment by kr8n3r** [comment]
use Zendesk api and set teh email template there?

**Comment by 0atman** [comment]
@kr8n3r Looks good, I'm diving into the `NotifyClient` in `lib/notify` :ok_hand:

**Comment by kr8n3r** [comment]
password reset uses notify as well

**Comment by 0atman** [comment]
Yeah, that's what I'm basing my code on, will push in an hourish

**Comment by kr8n3r** [comment]
not lookign over, just here coz merging dependabot PRs

you can login to notify admin and create a test key if you need it

**Comment by kr8n3r** [comment]
closing in favour of https://github.com/alphagov/paas-admin/pull/2012

**Pull request closed without merging**
