### PR TITLE
[#165345614] Add S3 Buckets to the pricing calculator

### PR DESCRIPTION
**Pull request by 46bit**
What
----

Includes S3 buckets in the pricing calculator. See commit message for full details.

How to review
-------------

* Code review;
* See if you are happy with how it is displayed in my environment **TODO: LINK**.

Who can review
---------------

Not @46bit.

### CODE REVIEW

**Comment by 46bit** [comment]
`aws-s3-bucket default` won't work as the name of the row in the Pricing Calculator. It isn't descriptive, but more importantly its length breaks the `app` row onto two lines:

Screen Shot 2019-04-17 at 14 54 16

**Comment by 46bit** [comment]
I think this is a *bit* better:

Screen Shot 2019-04-17 at 16 22 15

**Comment by 46bit** [comment]
There are no tests that it prints `default` if there are also non-default plans. That is because there is complex logic for how the plaintext pricing plan names are transformed, and such a test would be a nightmare to put together.

**Comment by tlwr** [comment]
Screen Shot 2019-04-18 at 17 18 02

4️⃣:two::zero:

**Pull request merged**
