### PR TITLE
Update metrics user range input and page layout

### PR DESCRIPTION
**Pull request by kr8n3r**
Co-authored with @paroxp 

What
----

**Problem:**
Screen reader users were initially unsure how to populate the ‘Start time’ and ‘End time’ input fields. The ‘value’ applied is of an American format and not what is visible on screen.

The value attribute is set to an American date format which reads to screen reader users backwards and may confuse some users as this contradicts what is displayed in the input field.

**Solution:**
Replace `input type="date-time"` date-picker with a Date input (and time input) components fields as is recommended by the GOV.UK Design System.

If users enter an invalid date we populate the values from current date-time object.

This makes the change range container much longer.

We've updated the layout so that the graphs and tables take up 2/3 of the width and the other 1/3 is the range container, for the whole of the page.

We've also moved the text about the current time period out of the container to above the metrics.

Page `title` and main heading now have visually-hidden text with dates of the start/stop range

How to review
-------------

- checkout branch, run locally
- go to backing service metrics page
- check date input return metrics for a valid date or if left empty (or chars) values from today's date-time object
- check download CSV links contain correct values
- check that page title and main heading (including visually hidden text) match

Who can review
---------------

not @kr8n3r 

Visual changes
----

## Before
before

## After
after

### CODE REVIEW

**Comment by 46bit** [comment]
Visual feedback is that the heading prominence looks a bit strange. "Start date", "Start time", "End date" and "End time" all have the same headings. The two Start sections look no more connected to each other than do the two End sections. For screen-reader accessibility I'm happy merging this without addressing that.

**Review by 46bit — CHANGES_REQUESTED** [review]
I've found a bug. Reproduction instructions:
1. Run it locally (`git checkout metrics-update-layout`, `npm run start:stub-api` and `npm run start:with-stub-api`)
2. Go to the metrics page of a postgres ([link](http://0.0.0.0:3000/organisations/a7aff246-5f5b-4cf8-87d8-f316053e4a20/spaces/bc8d3381-390d-4bd7-8c71-25309900a2e3/services/0d632575-bb06-4ea5-bb19-a451a9644d92/metrics))
3. The time period defaults to being for the last 24 hours
4. Don't edit the date/time form fields, but click Update
5. The start and end form fields change to both be the current time

This seems to happen sometimes when changing the date/time, but that's the easiest way to trigger it.

**Comment by kr8n3r** [comment]
> that the heading prominence looks a bit strange. "Start date", "Start time", "End date" and "End time" all have the same headings and same spacing. The two Start sections look no more connected to each other than to the two E

yep, heading sizes are limited. have added a divider between start and end section for a bit for demarcation

**Comment by kr8n3r** [comment]
> I've found a bug. Reproduction instructions:
> 
> 1. Run it locally (`git checkout metrics-update-layout`, `npm run start:stub-api` and `npm run start:with-stub-api`)
> 2. Go to the metrics page of a postgres ([link](http://0.0.0.0:3000/organisations/a7aff246-5f5b-4cf8-87d8-f316053e4a20/spaces/bc8d3381-390d-4bd7-8c71-25309900a2e3/services/0d632575-bb06-4ea5-bb19-a451a9644d92/metrics))
> 3. The time period defaults to being for the last 24 hours
> 4. Don't edit the date/time form fields, but click Update
> 5. The start and end form fields change to both be the current time
> 
> This seems to happen sometimes when changing the date/time, but that's the easiest way to trigger it.

seems like there are two page renders (or something) on form submit as it logs

```
range start: Moment<2020-09-21T12:56:00+01:00>
range stop: Moment<2020-09-22T12:56:00+01:00>
range start: Moment<2020-09-22T12:56:00+01:00>
range stop: Moment<2020-09-22T12:56:00+01:00>
```

**Comment by kr8n3r** [comment]
> I've found a bug. Reproduction instructions:
> 
> 1. Run it locally (`git checkout metrics-update-layout`, `npm run start:stub-api` and `npm run start:with-stub-api`)
> 2. Go to the metrics page of a postgres ([link](http://0.0.0.0:3000/organisations/a7aff246-5f5b-4cf8-87d8-f316053e4a20/spaces/bc8d3381-390d-4bd7-8c71-25309900a2e3/services/0d632575-bb06-4ea5-bb19-a451a9644d92/metrics))
> 3. The time period defaults to being for the last 24 hours
> 4. Don't edit the date/time form fields, but click Update
> 5. The start and end form fields change to both be the current time
> 
> This seems to happen sometimes when changing the date/time, but that's the easiest way to trigger it.

yep bad validation 🤦  
have made a change to the validate and what we do if date is not valid

**Comment by kr8n3r** [comment]
@46bit does "changes requested" tag stlil apply?

**Comment by 46bit** [comment]
@kr8n3r no, I haven't re-reviewed it since your fixes. I'm a bit busy dealing with support alerts--pair with Rafal and he can approve it?

**Comment by AP-Hunt** [comment]
Visually it looks fine, and the title and visually hidden text line up. I spotted two things though:

1. The CSV download URLs are using a human friendly date format, when I'd expect them to use ISO 8601 (or similar). Is that an affordance for accessibility? E.g.

`http://0.0.0.0:3000/organisations/a7aff246-5f5b-4cf8-87d8-f316053e4a20/spaces/bc8d3381-390d-4bd7-8c71-25309900a2e3/services/0d632575-bb06-4ea5-bb19-a451a9644d92/metrics/download?rangeStart=Tue+Oct+06+2020+12%3A27%3A00+GMT%2B0100&rangeStop=Tue+Oct+06+2020+12%3A27%3A00+GMT%2B0100&metric=mFreeStorageSpace&units=Bytes`

2. We need to provide a better error page when validating the inputs in the form. For example, if I enter the date `32/10/2020`, I get a screen like the below. 

image

**Review by AP-Hunt — CHANGES_REQUESTED** [review]
See previous comment >.<

**Comment by kr8n3r** [comment]
> 1. The CSV download URLs are using a human friendly date format, when I'd expect them to use ISO 8601 (or similar). Is that an affordance for accessibility? E.g.
> 
> `http://0.0.0.0:3000/organisations/a7aff246-5f5b-4cf8-87d8-f316053e4a20/spaces/bc8d3381-390d-4bd7-8c71-25309900a2e3/services/0d632575-bb06-4ea5-bb19-a451a9644d92/metrics/download?rangeStart=Tue+Oct+06+2020+12%3A27%3A00+GMT%2B0100&rangeStop=Tue+Oct+06+2020+12%3A27%3A00+GMT%2B0100&metric=mFreeStorageSpace&units=Bytes`
> 

url is the byproduct of making this change as the user provided params get passed around. same is reflected in the url, for example
```
http://0.0.0.0:3000/organisations/a7aff246-5f5b-4cf8-87d8-f316053e4a20/spaces/bc8d3381-390d-4bd7-8c71-25309900a2e3/services/0d632575-bb06-4ea5-bb19-a451a9644d92/metrics?_csrf=1eorxhz4-Oswcy1x1epIMMQow0bBQwiU1az0&rangeStart%5Bday%5D=01&rangeStart%5Bmonth%5D=10&rangeStart%5Byear%5D=2020&rangeStart%5Bhour%5D=13&rangeStart%5Bminute%5D=10&rangeStop%5Bday%5D=06&rangeStop%5Bmonth%5D=10&rangeStop%5Byear%5D=2020&rangeStop%5Bhour%5D=13&rangeStop%5Bminute%5D=10
```
hitting that url sets the selected range and fill inputs. 
From an SRE (maintainer) perspective, would either of these be a hindrance or cause confusion?

> 1. We need to provide a better error page when validating the inputs in the form. For example, if I enter the date `32/10/2020`, I get a screen like the below.
> 
> image

for missing inputs that are in the past we fill the data with values from current datetime
For anything older than [370 days](https://github.com/alphagov/paas-admin/blob/master/src/components/service-metrics/controllers.tsx#L44) [and the future](https://github.com/alphagov/paas-admin/blob/master/src/components/service-metrics/controllers.tsx#L68-L87), the application throws a similar style message

I will have a look if we can populate from current date-time (minus say 1 hour) for that scenario as well

**Comment by kr8n3r** [comment]
added commit to manage rangeStart date in the future scenario

**Comment by 46bit** [comment]
I think we can look to ship this. Getting the download urls right would be worthwhile but I don't think there's a big user need yet (happy to be proven wrong.)

**Review by 46bit — APPROVED** [review]
Tested it again locally; looks good to me

**Pull request merged**
